import { AuditRequestSchema } from '@/lib/schemas'
import { runAudit } from '@/data/martech-tools'
import { Resend } from 'resend'

function buildEmailHtml(
  result: ReturnType<typeof runAudit>,
  companyName?: string,
): string {
  const scoreColor =
    result.stackScore >= 80
      ? '#22c55e'
      : result.stackScore >= 60
        ? '#eab308'
        : result.stackScore >= 40
          ? '#f97316'
          : '#ef4444'

  const scoreLabel =
    result.stackScore >= 80
      ? 'Optimized'
      : result.stackScore >= 60
        ? 'Good'
        : result.stackScore >= 40
          ? 'Needs Work'
          : 'Critical'

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>MarTech Stack Audit Report</title>
</head>
<body style="font-family: Arial, sans-serif; background: #0f172a; color: #e2e8f0; margin: 0; padding: 20px;">
  <div style="max-width: 640px; margin: 0 auto; background: #1e293b; border-radius: 12px; overflow: hidden;">
    <div style="background: linear-gradient(135deg, #6366f1, #8b5cf6); padding: 32px; text-align: center;">
      <h1 style="margin: 0; color: #fff; font-size: 24px;">MarTech Stack Audit Report</h1>
      ${companyName ? `<p style="margin: 8px 0 0; color: rgba(255,255,255,0.8);">${companyName}</p>` : ''}
    </div>

    <div style="padding: 32px;">
      <div style="text-align: center; margin-bottom: 32px;">
        <div style="display: inline-block; background: #0f172a; border-radius: 50%; width: 120px; height: 120px; line-height: 120px; font-size: 48px; font-weight: bold; color: ${scoreColor};">
          ${result.stackScore}
        </div>
        <p style="margin: 8px 0 0; font-size: 18px; color: ${scoreColor}; font-weight: bold;">${scoreLabel}</p>
      </div>

      <div style="display: flex; gap: 16px; margin-bottom: 32px;">
        <div style="flex: 1; background: #0f172a; padding: 16px; border-radius: 8px; text-align: center;">
          <div style="font-size: 24px; font-weight: bold; color: #e2e8f0;">$${result.totalMonthlyCost.toLocaleString()}</div>
          <div style="font-size: 12px; color: #94a3b8; margin-top: 4px;">Total Monthly Cost</div>
        </div>
        <div style="flex: 1; background: #0f172a; padding: 16px; border-radius: 8px; text-align: center;">
          <div style="font-size: 24px; font-weight: bold; color: #ef4444;">$${result.estimatedWaste.toLocaleString()}</div>
          <div style="font-size: 12px; color: #94a3b8; margin-top: 4px;">Estimated Monthly Waste</div>
        </div>
        <div style="flex: 1; background: #0f172a; padding: 16px; border-radius: 8px; text-align: center;">
          <div style="font-size: 24px; font-weight: bold; color: #e2e8f0;">${result.selectedTools.length}</div>
          <div style="font-size: 12px; color: #94a3b8; margin-top: 4px;">Tools Audited</div>
        </div>
      </div>

      ${
        result.overlaps.length > 0
          ? `
      <h2 style="color: #f97316; margin: 0 0 16px; font-size: 18px;">⚠️ Overlapping Tools (${result.overlaps.length})</h2>
      ${result.overlaps
        .map(
          (o) => `
      <div style="background: #0f172a; border-left: 3px solid #f97316; padding: 16px; margin-bottom: 12px; border-radius: 0 8px 8px 0;">
        <p style="margin: 0 0 8px; font-weight: bold; color: #e2e8f0;">${o.message}</p>
        <p style="margin: 0 0 8px; color: #94a3b8; font-size: 14px;">${o.recommendation}</p>
        <p style="margin: 0; color: #22c55e; font-size: 14px; font-weight: bold;">Potential savings: $${o.monthlySavings}/month</p>
      </div>`,
        )
        .join('')}`
          : ''
      }

      ${
        result.gaps.length > 0
          ? `
      <h2 style="color: #ef4444; margin: 24px 0 16px; font-size: 18px;">🚨 Stack Gaps (${result.gaps.length})</h2>
      ${result.gaps
        .map(
          (g) => `
      <div style="background: #0f172a; border-left: 3px solid #ef4444; padding: 16px; margin-bottom: 12px; border-radius: 0 8px 8px 0;">
        <p style="margin: 0 0 8px; font-weight: bold; color: #e2e8f0;">${g.message}</p>
        <p style="margin: 0; color: #94a3b8; font-size: 14px;">${g.recommendation}</p>
      </div>`,
        )
        .join('')}`
          : ''
      }

      <h2 style="color: #6366f1; margin: 24px 0 16px; font-size: 18px;">✅ Recommendations</h2>
      <ol style="padding-left: 20px; margin: 0;">
        ${result.recommendations.map((r) => `<li style="color: #94a3b8; margin-bottom: 8px; font-size: 14px;">${r}</li>`).join('')}
      </ol>
    </div>

    <div style="background: #0f172a; padding: 16px; text-align: center;">
      <p style="margin: 0; color: #475569; font-size: 12px;">Generated by MarTech Stack Auditor · stackauditor.io</p>
    </div>
  </div>
</body>
</html>`
}

export async function POST(request: Request) {
  let body: unknown
  try {
    body = await request.json()
  } catch {
    return Response.json({ error: 'Invalid JSON' }, { status: 400 })
  }

  const parsed = AuditRequestSchema.safeParse(body)
  if (!parsed.success) {
    return Response.json(
      { error: 'Validation failed', issues: parsed.error.issues },
      { status: 422 },
    )
  }

  const { selectedTools, email, companyName } = parsed.data
  const result = runAudit(selectedTools)

  if (email && process.env.RESEND_API_KEY) {
    try {
      const resend = new Resend(process.env.RESEND_API_KEY)
      await resend.emails.send({
        from: 'reports@stackauditor.io',
        to: email,
        subject: `Your MarTech Stack Audit Report${companyName ? ` — ${companyName}` : ''}`,
        html: buildEmailHtml(result, companyName),
      })
    } catch {
      // Email sending is best-effort; don't fail the request
    }
  }

  return Response.json(result)
}
